### ISSUE TITLE
[Chore] Repository 초기 세팅

### ISSUE THREAD

**Issue by hyesuuou** [TeamCARDNA/Cardna-iOS#1]
- [x] .gitignore
- [x] merge 막기
- [x] 깃허브 슬랙 연동하기
- [x] 깃허브 템플릿 만들기

**Comment by ningpop** [comment]
앗트.. 깃허브 슬랙 연동이 씨워터의 to-do에 있는지 모르고 닝팝이 해버렸슴,,,

**Comment by hyesuuou** [comment]
@ningpop 오히려좋아!!!!!
