### ISSUE TITLE
[Feat] 카드팩 (나일때) 목록 불러오기 서버연결

### ISSUE THREAD

**Issue by meenyweeny** [TeamCARDNA/Cardna-iOS#183]
## Issue

카드팩 (나일때) 목록 불러오기 서버연결

## To-do

- [ ] 카드팩 (나일때) 목록 불러오기 서버연결

**Comment by hyesuuou** [comment]
![image](https://user-images.githubusercontent.com/68391767/150214834-5cf4fe36-03dc-48f9-9a78-dd4d5dcbfa14.png)
이거쓰삼

**Comment by hyesuuou** [comment]
@meenyweeny

**Comment by meenyweeny** [comment]
오키! 내일 홍할ㅇ에서 하겠씀둥~!
